// Sending JWT token in headers

axios.get("/protected", {
  headers: {
    Authorization: "Bearer YOUR_TOKEN"
  }
});

/* Authentication Tokens are security credentials used to verify the identity of a user or system after they successfully log in. Instead of sending a username and password with every request, a token is issued once and then used to authenticate subsequent requests.

1. What is an Authentication Token?

An authentication token is a unique string of characters generated by a server after a user logs in successfully. The client (browser, mobile app, or API consumer) stores this token and sends it with each request to prove the user is authenticated.

Simple idea:

User logs in with username + password

Server verifies credentials

Server generates a token

Client stores the token

Client sends token in future requests

Server validates the token

2. Why Authentication Tokens are Used

Tokens solve several problems with traditional session-based authentication.

Advantages

No need to send password repeatedly

Stateless authentication (server does not need to store sessions)

Works well with APIs and microservices

Improves security and scalability

Used widely in modern web apps and mobile apps

3. How Authentication Tokens Work (Step-by-Step)
Step 1 – Login Request

The client sends login credentials to the server.

POST /login
Content-Type: application/json

{
  "username": "anila",
  "password": "123456"
}
Step 2 – Server Generates Token

If credentials are valid, the server generates a token.

Example token:

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

Server response:

{
  "token": "abc123xyz456"
}
Step 3 – Client Stores Token

The token is stored in:

Local Storage

Session Storage

HTTP-only Cookies

Example:

localStorage.setItem("token", "abc123xyz456");
Step 4 – Sending Token with Requests

The client sends the token in the Authorization header.

GET /profile
Authorization: Bearer abc123xyz456
Step 5 – Server Verifies Token

Server checks:

Is token valid?

Has token expired?

Was token signed by the server?

If valid → request is processed.

4. Types of Authentication Tokens
1. Bearer Token

Most common token used in APIs.

Example:

Authorization: Bearer abc123xyz456

Used with:

REST APIs

OAuth

JWT

2. JSON Web Token (JWT)

A self-contained token that stores user information.

Structure of JWT:

Header.Payload.Signature

Example:

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
.
eyJ1c2VySWQiOjEyMywibmFtZSI6IkFuaWxhIn0
.
SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

JWT contains:

userId

roles

expiration time

3. Refresh Token

Used to generate a new access token when the current token expires.

Flow:

Access Token → short lifetime
Refresh Token → long lifetime
5. Example Using JavaScript (Frontend)

Login and store token.

fetch("https://api.example.com/login", {
  method: "POST",
  headers: {
    "Content-Type": "application/json"
  },
  body: JSON.stringify({
    username: "anila",
    password: "123456"
  })
})
.then(res => res.json())
.then(data => {
  localStorage.setItem("token", data.token);
});
Sending Authenticated Request
const token = localStorage.getItem("token");

fetch("https://api.example.com/profile", {
  method: "GET",
  headers: {
    "Authorization": `Bearer ${token}`
  }
})
.then(res => res.json())
.then(data => console.log(data));
6. Token vs Session Authentication
Feature	Token Authentication	Session Authentication
Storage	Client side	Server side
Scalability	High	Lower
Used in APIs	Yes	Rare
Stateless	Yes	No */